DROP DATABASE IF EXISTS db_ip;
CREATE DATABASE db_ip;

DROP TABLE IF EXISTS db_ip.user;
CREATE TABLE db_ip.user(
  id INT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID PK',
  start VARCHAR(255)NOT NULL COMMENT '起始IP',
  end VARCHAR(255)NOT NULL COMMENT '终止IP',
  address VARCHAR(255)NOT NULL COMMENT 'IP地址'
)COMMENT 'IP表';